theme: jekyll-theme-minimal
title: "Peixian Ma "
logo: "mylogo.png"
description: "<p>◽ Master of Philosophy
<br>◽ DSA Thrust, Information Hub
<br>◽ The Hong Kong University of Science and Technology (Guangzhou)</p>

<small>Email: mpx0222@qq.com</small>
<br>
<br> ◽ MPhil in HKUSTGZ（2023-2025）
<br> ◽ B.Eng. in JNU（2019-2023）"

